import { useState } from "react";
import { ArrowUpRight, Check, Download, Mail, MapPin, Moon, Phone, Sun } from "lucide-react";

const projects = [
  { no: "01", title: "SAP ↔ Unicommerce", text: "Connected SAP ERP workflows with a third-party commerce platform through integration, data mapping, and process coordination.", tags: ["SAP", "Integration", "Data mapping"] },
  { no: "02", title: "SAP + BEAS Manufacturing", text: "Supported manufacturing operations with BEAS production flows, inventory visibility, and reliable issue and receipt transactions.", tags: ["SAP B1", "BEAS", "Manufacturing"] },
  { no: "03", title: "WMS / FEFO / Picklist", text: "Improved warehouse-facing processes with clearer item movement, picking logic, and operational reporting.", tags: ["WMS", "FEFO", "Picklist"] },
  { no: "04", title: "SAP Web / Mobile Portal", text: "Built SAP-integrated portals and mobile workflows that made Sales, Purchase, Inventory, and Expense operations easier to access.", tags: ["Portals", "Mobile", "Workflow"] },
  { no: "05", title: "SQL / HANA Reporting", text: "Created stored procedures, validation logic, and reports that helped teams reach reliable operational insight faster.", tags: ["SQL", "HANA", "Reporting"] },
  { no: "06", title: "E-Invoicing / Automation", text: "Implemented process automation and e-invoicing solutions to reduce manual work and accelerate Accounts Receivable processing.", tags: ["Automation", "E-invoicing", "AR"] },
  { no: "07", title: "SAP ↔ Telegram Automation with n8n", text: "Personal project exploring automated SAP-to-Telegram integration with n8n for notifications, workflow triggers, and faster operational communication.", tags: ["n8n", "SAP", "Telegram"] },
];

const whatIDo = ["Business Analysis", "SAP / ERP", "Integration", "Data & SQL", "Automation", "Solution Delivery"];
const architecture = ["REST APIs", "SAP Service Layer", "System Integration", "Event-Driven Architecture", "Pub/Sub", "Microservices"];
const businessAnalysis = ["Requirements", "Process Mapping", "Gap Analysis", "Functional Documentation", "UAT", "Defect Management"];
const technical = ["SAP", "SAP Business One", "SQL", "SAP HANA", "REST APIs", "BEAS", "n8n", "Automation", "Data Mapping"];
const toolkitDetails: Record<string, { title: string; description: string; tools: string[] }> = {
  "Business Analysis": { title: "Business Analysis", description: "Translate business needs into clear processes, functional requirements, and testable outcomes.", tools: ["Requirements", "Process mapping", "Gap analysis", "UAT"] },
  "SAP / ERP": { title: "SAP / ERP", description: "Design and support SAP Business One workflows across sales, purchasing, inventory, finance, and operations.", tools: ["SAP Business One", "SAP Service Layer", "BEAS", "Functional consulting"] },
  "Integration": { title: "Integration", description: "Connect ERP and external systems so information moves reliably between teams, portals, and platforms.", tools: ["REST APIs", "Unicommerce", "Data mapping", "System integration"] },
  "Data & SQL": { title: "Data & SQL", description: "Use SQL and HANA to validate data, build reports, troubleshoot issues, and improve decision-making speed.", tools: ["SQL", "SAP HANA", "Stored procedures", "Reporting"] },
  "Automation": { title: "Automation", description: "Reduce manual work through workflow automation, notifications, and practical process improvements.", tools: ["n8n", "Workflow automation", "Telegram integration", "E-invoicing"] },
  "Solution Delivery": { title: "Solution Delivery", description: "Move from requirement to reliable release through documentation, testing, stakeholder alignment, and support.", tools: ["Documentation", "UAT", "Defect management", "Production support"] },
};
const experience = [
  { year: "2024 — Present", title: "Business Analyst Team Lead", company: "FieldNXT Pvt. Ltd", detail: "Leading SAP-integrated portals, workflow automation, BEAS manufacturing, SQL/HANA solutions, and third-party integrations.", skills: ["Team leadership", "SAP integrations", "BEAS", "Automation"] },
  { year: "2023 — 2024", title: "SAP Business One Functional Consultant", company: "Indus Novature Softech Pvt. Ltd", detail: "Supported SAP B1 implementations, production reporting, process documentation, and user adoption.", skills: ["SAP B1", "Functional consulting", "UAT", "Documentation"] },
  { year: "2020 — 2022", title: "Financial Analyst", company: "CA Asha Zachariah & Co", detail: "Delivered reporting and analysis for 10+ clients, improved data validation, and supported audit and compliance work.", skills: ["Financial analysis", "Reporting", "Data validation", "Audit support"] },
  { year: "2015 — 2020", title: "Accountant / Audit Executive", company: "CA Alex Kuriakose & Co", detail: "Built a strong foundation in accounting operations, audit support, reconciliations, and financial controls.", skills: ["Accounting", "Reconciliation", "Financial controls", "Audit"] },
];

// Use BASE_URL so image paths work both in local dev and when deployed
// under a GitHub Pages subpath (e.g. /Namad-Mohammed-BA-Portfolio/)
const PROFILE_IMG = `${import.meta.env.BASE_URL}images/profile.jpg`;
const CONTACT_QR_IMG = `${import.meta.env.BASE_URL}images/contact-qr.png`;

export default function Home() {
  const [selectedToolkit, setSelectedToolkit] = useState("Business Analysis");
  const [darkMode, setDarkMode] = useState(false);
  const activeToolkit = toolkitDetails[selectedToolkit];
  return (
    <div className={`consulting-portfolio ${darkMode ? "solarized-dark" : ""}`}>
      <header className="consulting-nav"><div className="page-container nav-content"><a className="consulting-brand" href="#top"><span className="brand-badge">NM</span><span>Namad Mohammed</span></a><nav><a href="#about">About</a><a href="#work">Projects</a><a href="#capabilities">Capabilities</a><a href="#contact">Contact</a></nav><div className="nav-actions"><button className="theme-toggle" type="button" onClick={() => setDarkMode((value) => !value)} aria-label={darkMode ? "Switch to Solarized light theme" : "Switch to Solarized dark theme"}>{darkMode ? <Sun size={14} /> : <Moon size={14} />}<span>{darkMode ? "Light" : "Dark"}</span></button><a className="nav-cta" href="#contact">Let&apos;s talk <ArrowUpRight size={14} /></a></div></div></header>

      <main id="top">
        <section className="consulting-hero"><div className="page-container hero-content"><div className="hero-copy"><div className="section-label">Business Analyst · ERP Consultant</div><h1>Business &amp; ERP<br /><em>Solutions.</em></h1><p>Integration, automation, and practical systems that help teams work with more clarity and less manual effort.</p><div className="hero-contact"><span><MapPin size={15} /> Trivandrum, Kerala</span><span><Mail size={15} /> namadmohammed0@gmail.com</span></div><div className="hero-actions"><a className="primary-cta" href="#work">View selected projects <ArrowUpRight size={15} /></a><button className="print-cta" type="button" onClick={() => window.print()}><Download size={15} /> Download as PDF</button></div></div><div className="hero-profile"><img className="profile-photo" src={PROFILE_IMG} alt="Namad Mohammed" /><div className="profile-caption"><strong>Namad Mohammed</strong><span>Business &amp; ERP Solutions<br />Integration · Automation</span></div></div></div></section>

        <section id="about" className="about-section"><div className="page-container about-grid"><div><div className="section-label">About me</div><h2>Connecting business<br /><em>needs with systems.</em></h2></div><div className="about-copy"><p>Business Analyst with experience in ERP integration, business process improvement, and automation. I work across business requirements, SAP ERP, SQL/HANA, third-party integrations, reporting, and user support.</p><p>My role is to make the path from “what the business needs” to “what the system should do” clear, testable, and useful.</p></div></div></section>

        <section className="what-section"><div className="page-container"><div className="merged-toolkit-heading"><div><div className="section-label">What I do · Technical</div><h2>What I do &amp;<br /><em>the working toolkit.</em></h2></div><p>Click a service card to reveal the tools, methods, and examples behind the work.</p></div><div className="pill-grid">{whatIDo.map((item, index) => <button className={`service-pill ${selectedToolkit === item ? "is-selected" : ""}`} key={item} type="button" onClick={() => setSelectedToolkit(item)}><span>0{index + 1}</span><strong>{item}</strong><ArrowUpRight size={15} /></button>)}</div><div className="toolkit-map"><div className="toolkit-simple-intro"><div className="section-label">The working toolkit</div><p>Select a capability above to reveal the tools, methods, and examples behind the work.</p></div><div className="toolkit-detail" aria-live="polite"><div className="section-label">Selected toolkit</div><h3>{activeToolkit.title}</h3><p>{activeToolkit.description}</p><div className="detail-tools">{activeToolkit.tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div></div></div></section>

        <section id="work" className="projects-section"><div className="page-container"><div className="section-heading"><div><div className="section-label">Selected projects</div><h2>Relevant work,<br /><em>clearly presented.</em></h2></div><p>Selected experience across ERP, manufacturing, portals, reporting, integration, automation, and a personal n8n project.</p></div><div className="project-grid">{projects.map((project, index) => <article className={`consulting-project ${index === 0 ? "project-highlight" : ""}`} key={project.no}><div className="project-top"><span>{project.no}</span><span>{index === 6 ? "PERSONAL PROJECT" : "SELECTED EXPERIENCE"}</span></div><h3>{project.title}</h3><p>{project.text}</p><div className="project-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><a href="#contact" className="project-link">Discuss this capability <ArrowUpRight size={14} /></a></article>)}</div></div></section>

        <section id="capabilities" className="capability-section"><div className="page-container capability-grid"><div><div className="section-label gold-label">Integration &amp; architecture</div><h2>Systems that<br /><em>connect.</em></h2><p>Comfortable working across the layers that move information between business teams, ERP, portals, and external platforms.</p></div><div className="capability-list">{architecture.map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong><Check size={14} /></div>)}</div></div></section>

        <section className="analysis-section"><div className="page-container analysis-grid"><div><div className="section-label">Business analysis</div><h2>From questions<br /><em>to action.</em></h2></div><div className="analysis-list">{businessAnalysis.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></div>)}</div></div></section>

        <section className="impact-section"><div className="page-container"><div className="section-label">Impact</div><div className="impact-grid"><div><strong>45%</strong><span>reduced dependency on SAP licenses through integrated portals and apps</span></div><div><strong>10–15</strong><span>hours saved per week through workflow automation</span></div><div><strong>50%</strong><span>reduction in reconciliation time through SQL/HANA validation</span></div><div><strong>30%</strong><span>lower system downtime and data transfer latency</span></div></div></div></section>

        <section className="experience-roadmap"><div className="page-container"><div className="section-label">Professional journey · present to past</div><div className="roadmap-heading"><div><h2>Experience that<br /><em>compounds.</em></h2></div><p>Starting with my current leadership role, each step branches into the skills that shaped the next stage of my work.</p></div><div className="roadmap">{experience.map((item, index) => <article className="roadmap-item" key={item.title}><div className="roadmap-marker"><span>{String(index + 1).padStart(2, "0")}</span></div><div className="roadmap-card"><div className="roadmap-year">{item.year}</div><h3>{item.title}</h3><strong>{item.company}</strong><p>{item.detail}</p><div className="roadmap-skills">{item.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></article>)}</div></div></section>

        <section className="education-section"><div className="page-container education-grid"><div><div className="section-label">About / education</div><h2>Grounded in<br /><em>business.</em></h2></div><div className="education-list"><div><span>Master&apos;s in Business Management</span><strong>University of Siena, Italy · 2016–2019</strong><p>Studied international management, corporate valuation, business law, strategic management, and financial accounting.</p></div><div><span>Bachelor of Commerce (B.Com)</span><strong>Mahatma Gandhi College, Kerala University · 2012–2015</strong><p>Focused on auditing, management accounting, costing, economics, and business law.</p></div><div><span>Languages</span><strong>English · Italian · Hindi · Malayalam</strong><p>Professional working communication across multicultural business and technology teams.</p></div></div></div></section>

        <section id="contact" className="contact-section"><div className="page-container contact-grid"><div><div className="section-label gold-label">Contact</div><h2>Let&apos;s build<br /><em>better workflows.</em></h2></div><div className="contact-details"><a href="mailto:namadmohammed0@gmail.com"><Mail size={17} /> namadmohammed0@gmail.com <ArrowUpRight size={15} /></a><a href="tel:+916238414128"><Phone size={17} /> +91 62384 14128 <ArrowUpRight size={15} /></a><span><MapPin size={17} /> Vembayam, Trivandrum, Kerala</span></div><div className="contact-qr"><img src={CONTACT_QR_IMG} alt="QR code with Namad Mohammed contact details and portfolio link" /><span>Scan to save my contact<br />details and open my portfolio</span></div></div></section>
      </main>
      <footer className="consulting-footer"><div className="page-container"><span>© {new Date().getFullYear()} Namad Mohammed</span><span>Business &amp; ERP Solutions | Integration | Automation</span></div></footer>
      <div className="print-portfolio" aria-hidden="true">
        <section className="print-page print-page-one"><div className="print-header"><strong>Namad Mohammed</strong><span>Business &amp; ERP Solutions | Integration | Automation</span></div><div className="print-hero"><div><div className="section-label">Business Analyst · ERP Consultant</div><h1>Business &amp; ERP<br /><em>Solutions.</em></h1><p>Integration, automation, and practical systems that help teams work with more clarity and less manual effort.</p><p className="print-contact">Trivandrum, Kerala · namadmohammed0@gmail.com · +91 62384 14128</p></div><img src={PROFILE_IMG} alt="Namad Mohammed" /></div><div className="print-divider" /><div className="print-two-col"><div><div className="section-label">About me</div><h2>Connecting business<br /><em>needs with systems.</em></h2></div><div><p>Business Analyst with experience in ERP integration, business process improvement, and automation. I work across business requirements, SAP ERP, SQL/HANA, third-party integrations, reporting, and user support.</p><p>I make the path from business need to system solution clear, testable, and useful.</p></div></div><div className="print-divider" /><div className="section-label">What I do</div><div className="print-chip-grid">{whatIDo.map((item) => <span key={item}>{item}</span>)}</div><div className="print-page-footer">01 / 03 · Profile &amp; capabilities</div></section>
        <section className="print-page print-page-two"><div className="print-header"><strong>Namad Mohammed</strong><span>Selected projects</span></div><div className="section-label">Selected projects</div><h2>Relevant work,<br /><em>clearly presented.</em></h2><div className="print-project-grid">{projects.map((project) => <article key={project.no}><div className="print-project-no">{project.no}</div><h3>{project.title}</h3><p>{project.text}</p><div className="print-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div><div className="print-page-footer">02 / 03 · Selected experience</div></section>
        <section className="print-page print-page-three"><div className="print-header"><strong>Namad Mohammed</strong><span>Capabilities &amp; contact</span></div><div className="print-two-col print-block"><div><div className="section-label">Integration &amp; architecture</div><h2>Systems that<br /><em>connect.</em></h2></div><div className="print-lines">{architecture.map((item, index) => <div key={item}><span>0{index + 1}</span>{item}</div>)}</div></div><div className="print-two-col print-block"><div><div className="section-label">Business analysis</div><h2>From questions<br /><em>to action.</em></h2></div><div className="print-lines">{businessAnalysis.map((item, index) => <div key={item}><span>0{index + 1}</span>{item}</div>)}</div></div><div className="print-roadmap"><div className="section-label">Professional journey · present to past</div><div className="print-roadmap-line">{experience.map((item) => <div key={item.title}><strong>{item.year}</strong><span>{item.title}</span><small>{item.company}</small><small>{item.skills.join(" · ")}</small></div>)}</div></div><div className="print-impact"><div className="section-label">Impact</div><strong>45% · 10–15 hrs/week · 50% · 30%</strong><p>SAP license dependency reduction · workflow automation savings · reconciliation time reduction · lower downtime and data transfer latency</p></div><div className="print-education"><div className="section-label">About / education</div><p><strong>Master&apos;s in Business Management</strong> · University of Siena, Italy · 2016–2019</p><p><strong>Bachelor of Commerce (B.Com)</strong> · Mahatma Gandhi College, Kerala University · 2012–2015</p><p><strong>Languages:</strong> English · Italian · Hindi · Malayalam</p></div><div className="print-contact-box"><div className="section-label">Contact</div><strong>namadmohammed0@gmail.com</strong><span>+91 62384 14128 · Vembayam, Trivandrum, Kerala</span><img className="print-contact-qr" src={CONTACT_QR_IMG} alt="QR code with Namad Mohammed contact details and portfolio link" /></div><div className="print-page-footer">03 / 03 · Architecture, journey, impact, education &amp; contact</div></section>
      </div>
    </div>
  );
}